# alembic.ini
# Migration configuration for Alembic in ЕПТА social database

[alembic]
script_location = alembic
prepend_sys_path = .
version_locations = %(here)s/alembic/versions

[logging]
default_level = INFO
